In [ ]:
import pandas as pd
import os

path = './MAMe_metadata/MAMe_labels.csv'

In [ ]:
dataframe = pd.read_csv(path, header=None)

In [ ]:
dict(zip(dataframe[1], dataframe[0]))

In [ ]:
dataframe.set_index(1)[0].to_dict()

In [ ]:
image_names = dataframe['Image file'].to_numpy()

In [ ]:
import cv2

images_path = os.path.join('./', 'MAMe_data_256', 'data_256')

are_all_256 = True

for image_name in image_names:
    image_path = os.path.join(images_path, image_name)
    image = cv2.imread(image_path)

    if image is None:
        print(image_name)

    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    if image.shape != (256, 256, 3):
        are_all_256 = False


print(are_all_256)

In [ ]:
import logging
from PIL import Image
from PIL import UnidentifiedImageError


for image_name in image_names:
    image_path = os.path.join(images_path, image_name)

    try:
        img = Image.open(image_path)
    
    except UnidentifiedImageError as e:
        logging.warning(e)
        logging.warning(f'Detected malformatted image: {image_name}. Skipping.')
        continue
    
    if img.mode == 'RGBA':
        logging.warning(f'Detected RGBA: {image_name}. Converting into RGB.')
        
    
    if img.mode == 'P':
        logging.warning(f'Detected P: {image_name}. Converting into RGB.')
       
    
    if img.mode == 'L':
        logging.warning(f'Detected BW image: {image_name}')


In [ ]:
img.show()

In [ ]:
'456.png Yep'.strip().split()

In [3]:
from tensorflow import keras
import tensorflow as tf

model = keras.Sequential()
model.add(keras.layers.Conv2D(8, (3, 3), activation='relu', input_shape=(256,256,3)))
model.add(keras.layers.MaxPooling2D(pool_size=(2, 2)))
model.add(keras.layers.Conv2D(16, 3, 3, activation='relu'))
model.add(keras.layers.MaxPooling2D(pool_size=(2, 2)))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(8, activation='relu'))
model.add(keras.layers.Dense(10, activation=(tf.nn.softmax)))

In [4]:
model_json = model.to_json()

In [12]:
import json
with open('model.json', 'w') as json_file:
    json.dump(json.loads(model_json), json_file, indent=4)

In [4]:
import numpy as np
result = np.unique([1,2,3,1,3,1,4,5,1], return_counts=True)
result

(array([1, 2, 3, 4, 5]),
 array([0, 1, 2, 6, 7], dtype=int64),
 array([4, 1, 2, 1, 1], dtype=int64))